language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - ree
  # Remove jruby as sqlite3 can't be installed on it
  # - jruby-18mode
  # - jruby-19mode
  # - jruby-head

before_install:
  # Setup display, used by webkit driver
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

